---
### Moscow ###
n7k1:
  hostname: n7k1  
  groups:
    - su
    - core
    - nexus
  data:
    role: core
    children: 
      Po1: catalyst19
      Po2: catalyst20
 
catalyst19:
  hostname: catalyst19
  platform: ios
  groups:
    - su
    - ios        
  data:
    role: access
    children: 
      Gi2/0/1: catalyst101
      Gi3/0/6: catalyst102
      
catalyst20:
  hostname: catalyst20  
  groups:
    - su
    - ios    
  data:
    role: access    
    children: 
      Gi3/0/32: catalyst103
      Gi1/0/37: catalyst107
      Po3: catalyst27      

catalyst27:
  hostname: catalyst27
  groups:
    - su
    - ios
  data:
    role: access
    children:
      gi1/0/10: ex2200-101

# Cisco Compact Switches
catalyst101:
  hostname: catalyst101
  groups:
    - su
    - ios    
  data:
    role: access     
    
catalyst102:
  hostname: catalyst102
  groups:
    - su
    - ios    
  data:
    role: access
    children: 

catalyst103:
  hostname: catalyst103
  groups:
    - su
    - ios    

catalyst104:
  hostname: catalyst104
  groups:
    - su
    - ios    
    
# Juniper ex2200
ex2200-101:
  hostname: ex2200-101
  groups:
    - su
    - junos
  data:
    role: access


### Samara####
sam-core:
  hostname: sam-core
  groups:    
    - core
    - ios
  data:
    role: core
    children:      
      Po1: sam-1
      Po2: sam-4
      
sam-1:
  hostname: sam-1
  groups:
    - sam   
    - huawei
  data:
    children:

sam-3:
  hostname: sam-3
  groups:
    - sam    
    - huawei

