---
n7k1:
  hostname: n7k1  
  groups:
    - su
    - core
    - nexus
  data:
    role: core
    parent:
    children: 
      Po14: catalist19
      Po12: catalist20
      Po22: catalyst23
      Po24: catalyst24
      Po25: catalyst25        
      Po31: catalyst31
      Po38: catalyst38

n7k2:
  hostname: n7k2  
  groups:
    - su
    - core
    - nexus
  data:
    role: core
    parent:
    children: 
      Po14: catalist19
      Po12: catalist20
      Po22: catalyst23
      Po24: catalyst24
      Po25: catalyst25        
      Po31: catalyst31
      Po38: catalyst38


catalyst19:
  hostname: catalyst19
  platform: ios
  groups:
    - su
    - ios        
  data:
    role: access
    parent: [n7k1, n7k2]
    children: 
      Gi2/0/1: catalyst110
      Gi3/0/6: catalyst105
      Gi2/0/32: catalyst104
      Gi3/0/6: catalyst106
      Gi3/0/22: catalyst108
      Po27: catalyst27

catalyst20:
  hostname: catalyst20
  platform: cisco_ios
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children: 
      Gi1/0/6: catalyst22
      Gi1/0/32: catalyst101
      Gi2/0/40: catalyst102
      Gi3/0/32: catalyst103
      Gi1/0/37: catalyst107
      Po3: catalyst26
      Po2: catalyst37

catalyst23:
  hostname: catalyst23
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children:
      Gi1/0/6: ex2200-101

catalyst24:
  hostname: catalyst24
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children:

catalyst25:
  hostname: catalyst25
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children:
      Gi0/3: catalyst109

catalyst27:
  hostname: catalyst27
  groups:
    - su
    - ios
  data:
    role: access
    parent: catalyst19
    children:

catalyst31:
  hostname: catalyst31
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children:

catalyst38:
  hostname: catalyst38
  groups:
    - su
    - ios    
  data:
    role: access
    parent: [n7k1, n7k2]
    children:

# Cisco Compact Switches
catalyst101:
  hostname: catalyst101
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 
    
catalyst102:
  hostname: catalyst102
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst103:
  hostname: catalyst103
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst104:
  hostname: catalyst104
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst105:
  hostname: catalyst105
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst106:
  hostname: catalyst106
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst107:
  hostname: catalyst107
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst108:
  hostname: catalyst108
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst109:
  hostname: catalyst109
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

catalyst110:
  hostname: catalyst110
  groups:
    - su
    - ios    
  data:
    role: access
    parent: 

# Juniper ex2200

ex2200-101:
  hostname: ex2200-101
  groups:
    - su
    - junos
  data:
    role: access
    parent: catalyst23


### SHAB ############
shab-core:
  hostname: shab-core
  groups:
    - shab
    - core
    - ios
  data:
    role: core
    parent:
    children:      
      Po1: shab-4a
      Po2: shab-3a
      Po3: shab-3b
      Po4: shab-8a 
      Po5: shab-1
      Po6: shab-4b
      Po7: shab-8a-7
      Po8: shab-7a
      Po128: shab-4a-srv

shab-1:
  hostname: shab-1
  groups:
    - shab    
    - huawei
  data:
    role: access
    parent: shab-core
    children:

shab-3a:
  hostname: shab-3a
  groups:
    - shab    
    - huawei
  data:
    role: access
    parent: shab-core
    children:  
  
shab-3b:
  hostname: shab-3b
  groups:
    - shab    
    - huawei
  data:
    role: access
    parent: shab-core
    children:

shab-4a:
  hostname: shab-4a
  groups:
    - shab    
    - huawei
  data:
    role: access
    parent: shab-core
    children:  

shab-4b:
  hostname: shab-4b
  groups:
    - shab    
    - huawei
  data:
    role: access
    parent: shab-core
    children:  

shab-7a:
  hostname: shab-7a
  groups:
    - shab    
    - ios
  data:
    role: access
    parent: shab-core
    children:  

shab-8a:
  hostname: shab-8a
  groups:
    - shab
    - access
    - huawei
  data:
    role: access
    parent: shab-core
    children:  

shab-8a-7:
  hostname: shab-8a-7
  groups:
    - shab    
    - ios
  data:
    role: access
    parent: shab-core
    children:  