---

n7k1:
  hostname: n7k1  
  groups:
    - su
    - core
    - nexus
  data:
    role: core
    parent:
    children: 
      Po14: catalist19
      Po12: catalist20
      Po24: catalyst24
      Po22: catalyst23        
      Po31: catalyst31
      Po38: catalyst38

n7k2:
  hostname: n7k2  
  groups:
    - su
    - core
    - nexus
  data:
    role: core
    parent:
    children: 
      Po14: catalist19
      Po12: catalist20
      Po24: catalyst24
      Po22: catalyst23        
      Po31: catalyst31
      Po38: catalyst38



catalyst19:
  hostname: catalyst19
  platform: ios
  groups:
    - su
    - ios
    - access    
  data:
    role: access
    parent: [n7k1, n7k2]
    children: 
      Gi2/0/1: catalyst110
      Gi3/0/6: catalyst105
      Gi2/0/32: catalyst104
      Gi3/0/6: catalyst106
      Gi3/0/22: catalyst108
      Po27: catalyst27

catalyst20:
  hostname: catalyst20
  platform: cisco_ios
  groups:
    - su
    - ios
    - access
  data:
    role: access
    parent: [n7k1, n7k2]
    children: 
      Gi1/0/6: catalyst22
      Gi1/0/32: catalyst101
      Gi2/0/40: catalyst102
      Gi3/0/32: catalyst103
      Gi1/0/37: catalyst107
      Po3: catalyst26
      Po2: catalyst37

### SHAB ############
shab-core:
  hostname: shab-core
  groups:
    - shab
    - core
    - ios
  data:
    role: core
    parent:
    children:      
      Po1: shab-4a
      Po2: shab-3a
      Po3: shab-3b
      Po4: shab-8a 
      Po5: shab-1
      Po6: shab-4b
      Po7: shab-8a-7
      Po8: shab-7a
      Po128: shab-4a-srv

shab-4a:
  hostname: shab-4a
  groups:
    - shab
    - access
    - huawei
  data:
    role: access
    parent: shab-core
    children:  
